### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ser** [pik/pypayd#2]
Hi, after recent changes something got wrong. A fresh installation cloned from github:

```
$ python pypayd.py 
Traceback (most recent call last):
  File "pypayd.py", line 9, in <module>
    from src import wallet, db, payments, api, config
  File "/opt/pypayd/src/wallet.py", line 69
    def __init__(self, *args, keypath=None, testnet=config.TESTNET,**kwargs): 
                                    ^
SyntaxError: invalid syntax
```

**Comment by pik** [comment]
Are you running Python2? `*args, x='foo', **kwargs` is python3 specific syntax.

**Comment by ser** [comment]
Thanks,
I really do not know why python was linked to 2.7, on 3.4 it works well, indeed.

Sorry for a false alarm and thanks for quick reaction!

PS. "addict" module should be added to pip listing.
